import { StudentTraining } from './type';

export const studentTrainings: StudentTraining[] = [
  {
    id: '1',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'completed',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
  {
    id: '2',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'inProgress',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
  {
    id: '3',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'dropped',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
  {
    id: '4',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'completed',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
  {
    id: '5',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'completed',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
  {
    id: '6',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'inProgress',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
  {
    id: '7',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'completed',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
  {
    id: '8',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'dropped',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
  {
    id: '9',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'completed',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
  {
    id: '10',
    industryName: 'Sina Gerard Nyiragarama',
    industryLocation: 'Kigali',
    trade: 'Welding',
    classLevel: 'Class Level 1',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    status: 'inProgress',
    location: 'Kigali - Ruhengeri Rd, ruhengeri',
    contact: '0788 305 122',
    competences: '?????????????',
    accommodationName: 'Hotel Rwanda',
    accommodationProvince: 'Kigali City',
    accommodationLocation: 'Downtown Kigali',
    accommodationContact: '0788 123 456',
    accommodationServices: 'Full Board, WiFi, Transport',
  },
];
