import { Industry } from './types';

export const industries: Industry[] = [
  {
    id: '1',
    name: 'Sina Gerard Nyirangarama',
    location: 'Nyirangarama, Rwanda',
    trades: ['Culinary Art', 'FOP'],
    studentsPlaced: 36,
    contact: 'info@sinagerard.rw',
    status: 'Active',
    companySupervisorName: 'Uwimana Natasha',
    companySupervisorContact: '0793990765',
  },
  {
    id: '2',
    name: 'M_Hotel',
    location: 'Kigali, Rwanda',
    trades: ['Culinary Art', 'Welding'],
    studentsPlaced: 54,
    contact: 'info@mhotel.com',
    status: 'Active',
    companySupervisorName: 'John Doe',
    companySupervisorContact: '0788888888',
  },
  {
    id: '3',
    name: 'Inyange Industries',
    location: 'Masaka, Rwanda',
    trades: ['FOP'],
    studentsPlaced: 10,
    contact: 'info@inyange.com',
    status: 'Active',
    companySupervisorName: 'Jane Smith',
    companySupervisorContact: '0799999999',
  },
  {
    id: '4',
    name: 'Marriot Hotel',
    location: 'Kigali, Rwanda',
    trades: ['Culinary Art'],
    studentsPlaced: 20,
    contact: 'info@marriot.com',
    status: 'Active',
    companySupervisorName: 'Peter Jones',
    companySupervisorContact: '0711111111',
  },
  {
    id: '5',
    name: 'Radisson Blu',
    location: 'Kigali, Rwanda',
    trades: ['Culinary Art'],
    studentsPlaced: 2,
    contact: 'info@radissonblu.com',
    status: 'Deactivated',
    companySupervisorName: 'Mary White',
    companySupervisorContact: '0722222222',
  },
  {
    id: '6',
    name: 'Volkswagen Rwanda',
    location: 'Kigali, Rwanda',
    trades: ['Welding'],
    studentsPlaced: 8,
    contact: 'info@vw.rw',
    status: 'Active',
    companySupervisorName: 'Chris Black',
    companySupervisorContact: '0733333333',
  },
  {
    id: '7',
    name: 'Serena Hotel',
    location: 'Kigali, Rwanda',
    trades: ['Culinary Art'],
    studentsPlaced: 0,
    contact: 'info@serena.com',
    status: 'Deactivated',
    companySupervisorName: 'Pat Green',
    companySupervisorContact: '0744444444',
  },
  {
    id: '8',
    name: 'Sulfo Rwanda',
    location: 'Kigali, Rwanda',
    trades: ['Welding'],
    studentsPlaced: 8,
    contact: 'info@sulfo.rw',
    status: 'Active',
    companySupervisorName: 'Sam Brown',
    companySupervisorContact: '0755555555',
  },
];
