import { Student } from './types';

export const students: Student[] = [
  {
    id: '1',
    name: 'Umutoni Teta',
    code: '1000283',
    trade: 'Welding',
    classLevel: 'Level 3',
    company: 'None',
    status: 'Active',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    province: 'Kigali',
    district: 'Kicukiro',
    parentName: 'Umutoni Teta',
    parentId: '1000283',
    parentContact: '0788888888',
    parentLocation: 'Kigali',
    parentProvince: 'Kigali',
    parentDistrict: 'Kicukiro',
  },
  {
    id: '2',
    name: 'Mazomaka Mike',
    code: '1000456',
    trade: 'Culinary Art',
    classLevel: 'Level 2',
    company: 'Sina Gerard Nyiragarama',
    status: 'Graduated',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    province: 'Kigali',
    district: 'Kicukiro',
    parentName: 'Umutoni Teta',
    parentId: '1000283',
    parentContact: '0788888888',
    parentLocation: 'Kigali',
    parentProvince: 'Kigali',
    parentDistrict: 'Kicukiro',
  },
  {
    id: '3',
    name: 'Mazomaka Mike',
    code: '1000456',
    trade: 'Culinary Art',
    classLevel: 'Level 2',
    company: 'Sina Gerard Nyiragarama',
    status: 'Dropped',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    province: 'Kigali',
    district: 'Kicukiro',
    parentName: 'Umutoni Teta',
    parentId: '1000283',
    parentContact: '0788888888',
    parentLocation: 'Kigali',
    parentProvince: 'Kigali',
    parentDistrict: 'Kicukiro',
  },
  {
    id: '4',
    name: 'Mazomaka Mike',
    code: '1000456',
    trade: 'Culinary Art',
    classLevel: 'Level 2',
    company: 'Sina Gerard Nyiragarama',
    status: 'Active',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    province: 'Kigali',
    district: 'Kicukiro',
    parentName: 'Umutoni Teta',
    parentId: '1000283',
    parentContact: '0788888888',
    parentLocation: 'Kigali',
    parentProvince: 'Kigali',
    parentDistrict: 'Kicukiro',
  },
  {
    id: '5',
    name: 'Mazomaka Mike',
    code: '1000456',
    trade: 'Culinary Art',
    classLevel: 'Level 2',
    company: 'Sina Gerard Nyiragarama',
    status: 'Graduated',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    province: 'Kigali',
    district: 'Kicukiro',
    parentName: 'Umutoni Teta',
    parentId: '1000283',
    parentContact: '0788888888',
    parentLocation: 'Kigali',
    parentProvince: 'Kigali',
    parentDistrict: 'Kicukiro',
  },
  {
    id: '6',
    name: 'Niyomungeli Aline',
    code: '1000287',
    trade: 'Welding',
    classLevel: 'Level 1',
    company: 'M-Hotel',
    status: 'Transferred',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    province: 'Kigali',
    district: 'Kicukiro',
  },
  {
    id: '7',
    name: 'Mazomaka Mike',
    code: '1000456',
    trade: 'Culinary Art',
    classLevel: 'Level 2',
    company: 'Sina Gerard Nyiragarama',
    status: 'Dropped',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    province: 'Kigali',
    district: 'Kicukiro',
    parentName: 'Umutoni Teta',
    parentId: '1000283',
    parentContact: '0788888888',
    parentLocation: 'Kigali',
    parentProvince: 'Kigali',
    parentDistrict: 'Kicukiro',
  },
  {
    id: '8',
    name: 'Niyomungeli Aline',
    code: '1000287',
    trade: 'Welding',
    classLevel: 'Level 1',
    company: 'M-Hotel',
    status: 'Transferred',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    province: 'Kigali',
    district: 'Kicukiro',
    parentName: 'Umutoni Teta',
    parentId: '1000283',
    parentContact: '0788888888',
    parentLocation: 'Kigali',
    parentProvince: 'Kigali',
    parentDistrict: 'Kicukiro',
  },
];
