/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyAccountRouteImport } from './routes/auth/verify-account'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardTrainingIndexRouteImport } from './routes/_authenticated/dashboard/training/index'
import { Route as AuthenticatedDashboardTeachersIndexRouteImport } from './routes/_authenticated/dashboard/teachers/index'
import { Route as AuthenticatedDashboardActivitiesIndexRouteImport } from './routes/_authenticated/dashboard/activities/index'
import { Route as AuthenticatedDashboardTrainingTrainingIdIndexRouteImport } from './routes/_authenticated/dashboard/training/$trainingId/index'
import { Route as AuthenticatedDashboardTeachersTeacherIdIndexRouteImport } from './routes/_authenticated/dashboard/teachers/$teacherId/index'
import { Route as AuthenticatedDashboardStudentsStudentIdIndexRouteImport } from './routes/_authenticated/dashboard/students/$studentId/index'
import { Route as AuthenticatedDashboardActivitiesWeekIdIndexRouteImport } from './routes/_authenticated/dashboard/activities/$weekId/index'
import { Route as AuthenticatedDashboardActivitiesWeekIdDateRouteImport } from './routes/_authenticated/dashboard/activities/$weekId/$date'

const AuthenticatedDashboardIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/',
)()
const AuthenticatedDashboardUsersLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/users',
)()
const AuthenticatedDashboardSettingsLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/settings',
)()
const AuthenticatedDashboardProfileLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/profile',
)()
const AuthenticatedDashboardNotificationsLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/notifications',
)()
const AuthenticatedDashboardStudentsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/students/',
)()
const AuthenticatedDashboardSchoolProfileIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/school-profile/',
)()
const AuthenticatedDashboardReportsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/reports/',
)()
const AuthenticatedDashboardLogbookIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/logbook/',
)()
const AuthenticatedDashboardIndustriesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/industries/',
)()
const AuthenticatedDashboardContractIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/contract/',
)()
const AuthenticatedDashboardComplaintsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/complaints/',
)()
const AuthenticatedDashboardLogbookDetailsLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/logbook/details',
)()
const AuthenticatedDashboardIndustriesRecommendedLazyRouteImport =
  createFileRoute('/_authenticated/dashboard/industries/recommended')()
const AuthenticatedDashboardIndustriesIndustryIdRouteLazyRouteImport =
  createFileRoute('/_authenticated/dashboard/industries/$industryId')()
const AuthenticatedDashboardContractContractIdRouteLazyRouteImport =
  createFileRoute('/_authenticated/dashboard/contract/$contractId')()
const AuthenticatedDashboardComplaintsComplaintIdRouteLazyRouteImport =
  createFileRoute('/_authenticated/dashboard/complaints/$complaintId')()
const AuthenticatedDashboardReportsReportIdIndexLazyRouteImport =
  createFileRoute('/_authenticated/dashboard/reports/$reportId/')()
const AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRouteImport =
  createFileRoute(
    '/_authenticated/dashboard/school-profile/sector-trade/$sectorTradeId',
  )()
const AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRouteImport =
  createFileRoute(
    '/_authenticated/dashboard/school-profile/academic-years/$academicYearId',
  )()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyAccountRoute = AuthVerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexLazyRoute =
  AuthenticatedDashboardIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/index.lazy').then((d) => d.Route),
  )
const AuthenticatedDashboardUsersLazyRoute =
  AuthenticatedDashboardUsersLazyRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/users.lazy').then((d) => d.Route),
  )
const AuthenticatedDashboardSettingsLazyRoute =
  AuthenticatedDashboardSettingsLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/settings.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardProfileLazyRoute =
  AuthenticatedDashboardProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/profile.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardNotificationsLazyRoute =
  AuthenticatedDashboardNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/notifications.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardStudentsIndexLazyRoute =
  AuthenticatedDashboardStudentsIndexLazyRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/students/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardSchoolProfileIndexLazyRoute =
  AuthenticatedDashboardSchoolProfileIndexLazyRouteImport.update({
    id: '/school-profile/',
    path: '/school-profile/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/school-profile/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardReportsIndexLazyRoute =
  AuthenticatedDashboardReportsIndexLazyRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/reports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardLogbookIndexLazyRoute =
  AuthenticatedDashboardLogbookIndexLazyRouteImport.update({
    id: '/logbook/',
    path: '/logbook/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/logbook/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardIndustriesIndexLazyRoute =
  AuthenticatedDashboardIndustriesIndexLazyRouteImport.update({
    id: '/industries/',
    path: '/industries/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/industries/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardContractIndexLazyRoute =
  AuthenticatedDashboardContractIndexLazyRouteImport.update({
    id: '/contract/',
    path: '/contract/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/contract/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardComplaintsIndexLazyRoute =
  AuthenticatedDashboardComplaintsIndexLazyRouteImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/complaints/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardTrainingIndexRoute =
  AuthenticatedDashboardTrainingIndexRouteImport.update({
    id: '/training/',
    path: '/training/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardTeachersIndexRoute =
  AuthenticatedDashboardTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardActivitiesIndexRoute =
  AuthenticatedDashboardActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardLogbookDetailsLazyRoute =
  AuthenticatedDashboardLogbookDetailsLazyRouteImport.update({
    id: '/logbook/details',
    path: '/logbook/details',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/logbook/details.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardIndustriesRecommendedLazyRoute =
  AuthenticatedDashboardIndustriesRecommendedLazyRouteImport.update({
    id: '/industries/recommended',
    path: '/industries/recommended',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/dashboard/industries/recommended.lazy'
    ).then((d) => d.Route),
  )
const AuthenticatedDashboardIndustriesIndustryIdRouteLazyRoute =
  AuthenticatedDashboardIndustriesIndustryIdRouteLazyRouteImport.update({
    id: '/industries/$industryId',
    path: '/industries/$industryId',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/dashboard/industries/$industryId/route.lazy'
    ).then((d) => d.Route),
  )
const AuthenticatedDashboardContractContractIdRouteLazyRoute =
  AuthenticatedDashboardContractContractIdRouteLazyRouteImport.update({
    id: '/contract/$contractId',
    path: '/contract/$contractId',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/dashboard/contract/$contractId/route.lazy'
    ).then((d) => d.Route),
  )
const AuthenticatedDashboardComplaintsComplaintIdRouteLazyRoute =
  AuthenticatedDashboardComplaintsComplaintIdRouteLazyRouteImport.update({
    id: '/complaints/$complaintId',
    path: '/complaints/$complaintId',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/dashboard/complaints/$complaintId/route.lazy'
    ).then((d) => d.Route),
  )
const AuthenticatedDashboardReportsReportIdIndexLazyRoute =
  AuthenticatedDashboardReportsReportIdIndexLazyRouteImport.update({
    id: '/reports/$reportId/',
    path: '/reports/$reportId/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/dashboard/reports/$reportId/index.lazy'
    ).then((d) => d.Route),
  )
const AuthenticatedDashboardTrainingTrainingIdIndexRoute =
  AuthenticatedDashboardTrainingTrainingIdIndexRouteImport.update({
    id: '/training/$trainingId/',
    path: '/training/$trainingId/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardTeachersTeacherIdIndexRoute =
  AuthenticatedDashboardTeachersTeacherIdIndexRouteImport.update({
    id: '/teachers/$teacherId/',
    path: '/teachers/$teacherId/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStudentsStudentIdIndexRoute =
  AuthenticatedDashboardStudentsStudentIdIndexRouteImport.update({
    id: '/students/$studentId/',
    path: '/students/$studentId/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardActivitiesWeekIdIndexRoute =
  AuthenticatedDashboardActivitiesWeekIdIndexRouteImport.update({
    id: '/activities/$weekId/',
    path: '/activities/$weekId/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRoute =
  AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRouteImport.update(
    {
      id: '/school-profile/sector-trade/$sectorTradeId',
      path: '/school-profile/sector-trade/$sectorTradeId',
      getParentRoute: () => AuthenticatedDashboardRouteRoute,
    } as any,
  ).lazy(() =>
    import(
      './routes/_authenticated/dashboard/school-profile/sector-trade/$sectorTradeId/route.lazy'
    ).then((d) => d.Route),
  )
const AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRoute =
  AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRouteImport.update(
    {
      id: '/school-profile/academic-years/$academicYearId',
      path: '/school-profile/academic-years/$academicYearId',
      getParentRoute: () => AuthenticatedDashboardRouteRoute,
    } as any,
  ).lazy(() =>
    import(
      './routes/_authenticated/dashboard/school-profile/academic-years/$academicYearId/route.lazy'
    ).then((d) => d.Route),
  )
const AuthenticatedDashboardActivitiesWeekIdDateRoute =
  AuthenticatedDashboardActivitiesWeekIdDateRouteImport.update({
    id: '/activities/$weekId/$date',
    path: '/activities/$weekId/$date',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/verify-account': typeof AuthVerifyAccountRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsLazyRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileLazyRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsLazyRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersLazyRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexLazyRoute
  '/dashboard/complaints/$complaintId': typeof AuthenticatedDashboardComplaintsComplaintIdRouteLazyRoute
  '/dashboard/contract/$contractId': typeof AuthenticatedDashboardContractContractIdRouteLazyRoute
  '/dashboard/industries/$industryId': typeof AuthenticatedDashboardIndustriesIndustryIdRouteLazyRoute
  '/dashboard/industries/recommended': typeof AuthenticatedDashboardIndustriesRecommendedLazyRoute
  '/dashboard/logbook/details': typeof AuthenticatedDashboardLogbookDetailsLazyRoute
  '/dashboard/activities': typeof AuthenticatedDashboardActivitiesIndexRoute
  '/dashboard/teachers': typeof AuthenticatedDashboardTeachersIndexRoute
  '/dashboard/training': typeof AuthenticatedDashboardTrainingIndexRoute
  '/dashboard/complaints': typeof AuthenticatedDashboardComplaintsIndexLazyRoute
  '/dashboard/contract': typeof AuthenticatedDashboardContractIndexLazyRoute
  '/dashboard/industries': typeof AuthenticatedDashboardIndustriesIndexLazyRoute
  '/dashboard/logbook': typeof AuthenticatedDashboardLogbookIndexLazyRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsIndexLazyRoute
  '/dashboard/school-profile': typeof AuthenticatedDashboardSchoolProfileIndexLazyRoute
  '/dashboard/students': typeof AuthenticatedDashboardStudentsIndexLazyRoute
  '/dashboard/activities/$weekId/$date': typeof AuthenticatedDashboardActivitiesWeekIdDateRoute
  '/dashboard/school-profile/academic-years/$academicYearId': typeof AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRoute
  '/dashboard/school-profile/sector-trade/$sectorTradeId': typeof AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRoute
  '/dashboard/activities/$weekId': typeof AuthenticatedDashboardActivitiesWeekIdIndexRoute
  '/dashboard/students/$studentId': typeof AuthenticatedDashboardStudentsStudentIdIndexRoute
  '/dashboard/teachers/$teacherId': typeof AuthenticatedDashboardTeachersTeacherIdIndexRoute
  '/dashboard/training/$trainingId': typeof AuthenticatedDashboardTrainingTrainingIdIndexRoute
  '/dashboard/reports/$reportId': typeof AuthenticatedDashboardReportsReportIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/verify-account': typeof AuthVerifyAccountRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsLazyRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileLazyRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsLazyRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersLazyRoute
  '/dashboard': typeof AuthenticatedDashboardIndexLazyRoute
  '/dashboard/complaints/$complaintId': typeof AuthenticatedDashboardComplaintsComplaintIdRouteLazyRoute
  '/dashboard/contract/$contractId': typeof AuthenticatedDashboardContractContractIdRouteLazyRoute
  '/dashboard/industries/$industryId': typeof AuthenticatedDashboardIndustriesIndustryIdRouteLazyRoute
  '/dashboard/industries/recommended': typeof AuthenticatedDashboardIndustriesRecommendedLazyRoute
  '/dashboard/logbook/details': typeof AuthenticatedDashboardLogbookDetailsLazyRoute
  '/dashboard/activities': typeof AuthenticatedDashboardActivitiesIndexRoute
  '/dashboard/teachers': typeof AuthenticatedDashboardTeachersIndexRoute
  '/dashboard/training': typeof AuthenticatedDashboardTrainingIndexRoute
  '/dashboard/complaints': typeof AuthenticatedDashboardComplaintsIndexLazyRoute
  '/dashboard/contract': typeof AuthenticatedDashboardContractIndexLazyRoute
  '/dashboard/industries': typeof AuthenticatedDashboardIndustriesIndexLazyRoute
  '/dashboard/logbook': typeof AuthenticatedDashboardLogbookIndexLazyRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsIndexLazyRoute
  '/dashboard/school-profile': typeof AuthenticatedDashboardSchoolProfileIndexLazyRoute
  '/dashboard/students': typeof AuthenticatedDashboardStudentsIndexLazyRoute
  '/dashboard/activities/$weekId/$date': typeof AuthenticatedDashboardActivitiesWeekIdDateRoute
  '/dashboard/school-profile/academic-years/$academicYearId': typeof AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRoute
  '/dashboard/school-profile/sector-trade/$sectorTradeId': typeof AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRoute
  '/dashboard/activities/$weekId': typeof AuthenticatedDashboardActivitiesWeekIdIndexRoute
  '/dashboard/students/$studentId': typeof AuthenticatedDashboardStudentsStudentIdIndexRoute
  '/dashboard/teachers/$teacherId': typeof AuthenticatedDashboardTeachersTeacherIdIndexRoute
  '/dashboard/training/$trainingId': typeof AuthenticatedDashboardTrainingTrainingIdIndexRoute
  '/dashboard/reports/$reportId': typeof AuthenticatedDashboardReportsReportIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/verify-account': typeof AuthVerifyAccountRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsLazyRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileLazyRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsLazyRoute
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersLazyRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexLazyRoute
  '/_authenticated/dashboard/complaints/$complaintId': typeof AuthenticatedDashboardComplaintsComplaintIdRouteLazyRoute
  '/_authenticated/dashboard/contract/$contractId': typeof AuthenticatedDashboardContractContractIdRouteLazyRoute
  '/_authenticated/dashboard/industries/$industryId': typeof AuthenticatedDashboardIndustriesIndustryIdRouteLazyRoute
  '/_authenticated/dashboard/industries/recommended': typeof AuthenticatedDashboardIndustriesRecommendedLazyRoute
  '/_authenticated/dashboard/logbook/details': typeof AuthenticatedDashboardLogbookDetailsLazyRoute
  '/_authenticated/dashboard/activities/': typeof AuthenticatedDashboardActivitiesIndexRoute
  '/_authenticated/dashboard/teachers/': typeof AuthenticatedDashboardTeachersIndexRoute
  '/_authenticated/dashboard/training/': typeof AuthenticatedDashboardTrainingIndexRoute
  '/_authenticated/dashboard/complaints/': typeof AuthenticatedDashboardComplaintsIndexLazyRoute
  '/_authenticated/dashboard/contract/': typeof AuthenticatedDashboardContractIndexLazyRoute
  '/_authenticated/dashboard/industries/': typeof AuthenticatedDashboardIndustriesIndexLazyRoute
  '/_authenticated/dashboard/logbook/': typeof AuthenticatedDashboardLogbookIndexLazyRoute
  '/_authenticated/dashboard/reports/': typeof AuthenticatedDashboardReportsIndexLazyRoute
  '/_authenticated/dashboard/school-profile/': typeof AuthenticatedDashboardSchoolProfileIndexLazyRoute
  '/_authenticated/dashboard/students/': typeof AuthenticatedDashboardStudentsIndexLazyRoute
  '/_authenticated/dashboard/activities/$weekId/$date': typeof AuthenticatedDashboardActivitiesWeekIdDateRoute
  '/_authenticated/dashboard/school-profile/academic-years/$academicYearId': typeof AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRoute
  '/_authenticated/dashboard/school-profile/sector-trade/$sectorTradeId': typeof AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRoute
  '/_authenticated/dashboard/activities/$weekId/': typeof AuthenticatedDashboardActivitiesWeekIdIndexRoute
  '/_authenticated/dashboard/students/$studentId/': typeof AuthenticatedDashboardStudentsStudentIdIndexRoute
  '/_authenticated/dashboard/teachers/$teacherId/': typeof AuthenticatedDashboardTeachersTeacherIdIndexRoute
  '/_authenticated/dashboard/training/$trainingId/': typeof AuthenticatedDashboardTrainingTrainingIdIndexRoute
  '/_authenticated/dashboard/reports/$reportId/': typeof AuthenticatedDashboardReportsReportIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/verify-account'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/complaints/$complaintId'
    | '/dashboard/contract/$contractId'
    | '/dashboard/industries/$industryId'
    | '/dashboard/industries/recommended'
    | '/dashboard/logbook/details'
    | '/dashboard/activities'
    | '/dashboard/teachers'
    | '/dashboard/training'
    | '/dashboard/complaints'
    | '/dashboard/contract'
    | '/dashboard/industries'
    | '/dashboard/logbook'
    | '/dashboard/reports'
    | '/dashboard/school-profile'
    | '/dashboard/students'
    | '/dashboard/activities/$weekId/$date'
    | '/dashboard/school-profile/academic-years/$academicYearId'
    | '/dashboard/school-profile/sector-trade/$sectorTradeId'
    | '/dashboard/activities/$weekId'
    | '/dashboard/students/$studentId'
    | '/dashboard/teachers/$teacherId'
    | '/dashboard/training/$trainingId'
    | '/dashboard/reports/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/verify-account'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/complaints/$complaintId'
    | '/dashboard/contract/$contractId'
    | '/dashboard/industries/$industryId'
    | '/dashboard/industries/recommended'
    | '/dashboard/logbook/details'
    | '/dashboard/activities'
    | '/dashboard/teachers'
    | '/dashboard/training'
    | '/dashboard/complaints'
    | '/dashboard/contract'
    | '/dashboard/industries'
    | '/dashboard/logbook'
    | '/dashboard/reports'
    | '/dashboard/school-profile'
    | '/dashboard/students'
    | '/dashboard/activities/$weekId/$date'
    | '/dashboard/school-profile/academic-years/$academicYearId'
    | '/dashboard/school-profile/sector-trade/$sectorTradeId'
    | '/dashboard/activities/$weekId'
    | '/dashboard/students/$studentId'
    | '/dashboard/teachers/$teacherId'
    | '/dashboard/training/$trainingId'
    | '/dashboard/reports/$reportId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/verify-account'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/complaints/$complaintId'
    | '/_authenticated/dashboard/contract/$contractId'
    | '/_authenticated/dashboard/industries/$industryId'
    | '/_authenticated/dashboard/industries/recommended'
    | '/_authenticated/dashboard/logbook/details'
    | '/_authenticated/dashboard/activities/'
    | '/_authenticated/dashboard/teachers/'
    | '/_authenticated/dashboard/training/'
    | '/_authenticated/dashboard/complaints/'
    | '/_authenticated/dashboard/contract/'
    | '/_authenticated/dashboard/industries/'
    | '/_authenticated/dashboard/logbook/'
    | '/_authenticated/dashboard/reports/'
    | '/_authenticated/dashboard/school-profile/'
    | '/_authenticated/dashboard/students/'
    | '/_authenticated/dashboard/activities/$weekId/$date'
    | '/_authenticated/dashboard/school-profile/academic-years/$academicYearId'
    | '/_authenticated/dashboard/school-profile/sector-trade/$sectorTradeId'
    | '/_authenticated/dashboard/activities/$weekId/'
    | '/_authenticated/dashboard/students/$studentId/'
    | '/_authenticated/dashboard/teachers/$teacherId/'
    | '/_authenticated/dashboard/training/$trainingId/'
    | '/_authenticated/dashboard/reports/$reportId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-account': {
      id: '/auth/verify-account'
      path: '/verify-account'
      fullPath: '/auth/verify-account'
      preLoaderRoute: typeof AuthVerifyAccountRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/students/': {
      id: '/_authenticated/dashboard/students/'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof AuthenticatedDashboardStudentsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/school-profile/': {
      id: '/_authenticated/dashboard/school-profile/'
      path: '/school-profile'
      fullPath: '/dashboard/school-profile'
      preLoaderRoute: typeof AuthenticatedDashboardSchoolProfileIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/reports/': {
      id: '/_authenticated/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/logbook/': {
      id: '/_authenticated/dashboard/logbook/'
      path: '/logbook'
      fullPath: '/dashboard/logbook'
      preLoaderRoute: typeof AuthenticatedDashboardLogbookIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/industries/': {
      id: '/_authenticated/dashboard/industries/'
      path: '/industries'
      fullPath: '/dashboard/industries'
      preLoaderRoute: typeof AuthenticatedDashboardIndustriesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/contract/': {
      id: '/_authenticated/dashboard/contract/'
      path: '/contract'
      fullPath: '/dashboard/contract'
      preLoaderRoute: typeof AuthenticatedDashboardContractIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/complaints/': {
      id: '/_authenticated/dashboard/complaints/'
      path: '/complaints'
      fullPath: '/dashboard/complaints'
      preLoaderRoute: typeof AuthenticatedDashboardComplaintsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/training/': {
      id: '/_authenticated/dashboard/training/'
      path: '/training'
      fullPath: '/dashboard/training'
      preLoaderRoute: typeof AuthenticatedDashboardTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/teachers/': {
      id: '/_authenticated/dashboard/teachers/'
      path: '/teachers'
      fullPath: '/dashboard/teachers'
      preLoaderRoute: typeof AuthenticatedDashboardTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/activities/': {
      id: '/_authenticated/dashboard/activities/'
      path: '/activities'
      fullPath: '/dashboard/activities'
      preLoaderRoute: typeof AuthenticatedDashboardActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/logbook/details': {
      id: '/_authenticated/dashboard/logbook/details'
      path: '/logbook/details'
      fullPath: '/dashboard/logbook/details'
      preLoaderRoute: typeof AuthenticatedDashboardLogbookDetailsLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/industries/recommended': {
      id: '/_authenticated/dashboard/industries/recommended'
      path: '/industries/recommended'
      fullPath: '/dashboard/industries/recommended'
      preLoaderRoute: typeof AuthenticatedDashboardIndustriesRecommendedLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/industries/$industryId': {
      id: '/_authenticated/dashboard/industries/$industryId'
      path: '/industries/$industryId'
      fullPath: '/dashboard/industries/$industryId'
      preLoaderRoute: typeof AuthenticatedDashboardIndustriesIndustryIdRouteLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/contract/$contractId': {
      id: '/_authenticated/dashboard/contract/$contractId'
      path: '/contract/$contractId'
      fullPath: '/dashboard/contract/$contractId'
      preLoaderRoute: typeof AuthenticatedDashboardContractContractIdRouteLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/complaints/$complaintId': {
      id: '/_authenticated/dashboard/complaints/$complaintId'
      path: '/complaints/$complaintId'
      fullPath: '/dashboard/complaints/$complaintId'
      preLoaderRoute: typeof AuthenticatedDashboardComplaintsComplaintIdRouteLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/reports/$reportId/': {
      id: '/_authenticated/dashboard/reports/$reportId/'
      path: '/reports/$reportId'
      fullPath: '/dashboard/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedDashboardReportsReportIdIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/training/$trainingId/': {
      id: '/_authenticated/dashboard/training/$trainingId/'
      path: '/training/$trainingId'
      fullPath: '/dashboard/training/$trainingId'
      preLoaderRoute: typeof AuthenticatedDashboardTrainingTrainingIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/teachers/$teacherId/': {
      id: '/_authenticated/dashboard/teachers/$teacherId/'
      path: '/teachers/$teacherId'
      fullPath: '/dashboard/teachers/$teacherId'
      preLoaderRoute: typeof AuthenticatedDashboardTeachersTeacherIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/students/$studentId/': {
      id: '/_authenticated/dashboard/students/$studentId/'
      path: '/students/$studentId'
      fullPath: '/dashboard/students/$studentId'
      preLoaderRoute: typeof AuthenticatedDashboardStudentsStudentIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/activities/$weekId/': {
      id: '/_authenticated/dashboard/activities/$weekId/'
      path: '/activities/$weekId'
      fullPath: '/dashboard/activities/$weekId'
      preLoaderRoute: typeof AuthenticatedDashboardActivitiesWeekIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/school-profile/sector-trade/$sectorTradeId': {
      id: '/_authenticated/dashboard/school-profile/sector-trade/$sectorTradeId'
      path: '/school-profile/sector-trade/$sectorTradeId'
      fullPath: '/dashboard/school-profile/sector-trade/$sectorTradeId'
      preLoaderRoute: typeof AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/school-profile/academic-years/$academicYearId': {
      id: '/_authenticated/dashboard/school-profile/academic-years/$academicYearId'
      path: '/school-profile/academic-years/$academicYearId'
      fullPath: '/dashboard/school-profile/academic-years/$academicYearId'
      preLoaderRoute: typeof AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/activities/$weekId/$date': {
      id: '/_authenticated/dashboard/activities/$weekId/$date'
      path: '/activities/$weekId/$date'
      fullPath: '/dashboard/activities/$weekId/$date'
      preLoaderRoute: typeof AuthenticatedDashboardActivitiesWeekIdDateRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthVerifyAccountRoute: typeof AuthVerifyAccountRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthVerifyAccountRoute: AuthVerifyAccountRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardNotificationsLazyRoute: typeof AuthenticatedDashboardNotificationsLazyRoute
  AuthenticatedDashboardProfileLazyRoute: typeof AuthenticatedDashboardProfileLazyRoute
  AuthenticatedDashboardSettingsLazyRoute: typeof AuthenticatedDashboardSettingsLazyRoute
  AuthenticatedDashboardUsersLazyRoute: typeof AuthenticatedDashboardUsersLazyRoute
  AuthenticatedDashboardIndexLazyRoute: typeof AuthenticatedDashboardIndexLazyRoute
  AuthenticatedDashboardComplaintsComplaintIdRouteLazyRoute: typeof AuthenticatedDashboardComplaintsComplaintIdRouteLazyRoute
  AuthenticatedDashboardContractContractIdRouteLazyRoute: typeof AuthenticatedDashboardContractContractIdRouteLazyRoute
  AuthenticatedDashboardIndustriesIndustryIdRouteLazyRoute: typeof AuthenticatedDashboardIndustriesIndustryIdRouteLazyRoute
  AuthenticatedDashboardIndustriesRecommendedLazyRoute: typeof AuthenticatedDashboardIndustriesRecommendedLazyRoute
  AuthenticatedDashboardLogbookDetailsLazyRoute: typeof AuthenticatedDashboardLogbookDetailsLazyRoute
  AuthenticatedDashboardActivitiesIndexRoute: typeof AuthenticatedDashboardActivitiesIndexRoute
  AuthenticatedDashboardTeachersIndexRoute: typeof AuthenticatedDashboardTeachersIndexRoute
  AuthenticatedDashboardTrainingIndexRoute: typeof AuthenticatedDashboardTrainingIndexRoute
  AuthenticatedDashboardComplaintsIndexLazyRoute: typeof AuthenticatedDashboardComplaintsIndexLazyRoute
  AuthenticatedDashboardContractIndexLazyRoute: typeof AuthenticatedDashboardContractIndexLazyRoute
  AuthenticatedDashboardIndustriesIndexLazyRoute: typeof AuthenticatedDashboardIndustriesIndexLazyRoute
  AuthenticatedDashboardLogbookIndexLazyRoute: typeof AuthenticatedDashboardLogbookIndexLazyRoute
  AuthenticatedDashboardReportsIndexLazyRoute: typeof AuthenticatedDashboardReportsIndexLazyRoute
  AuthenticatedDashboardSchoolProfileIndexLazyRoute: typeof AuthenticatedDashboardSchoolProfileIndexLazyRoute
  AuthenticatedDashboardStudentsIndexLazyRoute: typeof AuthenticatedDashboardStudentsIndexLazyRoute
  AuthenticatedDashboardActivitiesWeekIdDateRoute: typeof AuthenticatedDashboardActivitiesWeekIdDateRoute
  AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRoute: typeof AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRoute
  AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRoute: typeof AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRoute
  AuthenticatedDashboardActivitiesWeekIdIndexRoute: typeof AuthenticatedDashboardActivitiesWeekIdIndexRoute
  AuthenticatedDashboardStudentsStudentIdIndexRoute: typeof AuthenticatedDashboardStudentsStudentIdIndexRoute
  AuthenticatedDashboardTeachersTeacherIdIndexRoute: typeof AuthenticatedDashboardTeachersTeacherIdIndexRoute
  AuthenticatedDashboardTrainingTrainingIdIndexRoute: typeof AuthenticatedDashboardTrainingTrainingIdIndexRoute
  AuthenticatedDashboardReportsReportIdIndexLazyRoute: typeof AuthenticatedDashboardReportsReportIdIndexLazyRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardNotificationsLazyRoute:
      AuthenticatedDashboardNotificationsLazyRoute,
    AuthenticatedDashboardProfileLazyRoute:
      AuthenticatedDashboardProfileLazyRoute,
    AuthenticatedDashboardSettingsLazyRoute:
      AuthenticatedDashboardSettingsLazyRoute,
    AuthenticatedDashboardUsersLazyRoute: AuthenticatedDashboardUsersLazyRoute,
    AuthenticatedDashboardIndexLazyRoute: AuthenticatedDashboardIndexLazyRoute,
    AuthenticatedDashboardComplaintsComplaintIdRouteLazyRoute:
      AuthenticatedDashboardComplaintsComplaintIdRouteLazyRoute,
    AuthenticatedDashboardContractContractIdRouteLazyRoute:
      AuthenticatedDashboardContractContractIdRouteLazyRoute,
    AuthenticatedDashboardIndustriesIndustryIdRouteLazyRoute:
      AuthenticatedDashboardIndustriesIndustryIdRouteLazyRoute,
    AuthenticatedDashboardIndustriesRecommendedLazyRoute:
      AuthenticatedDashboardIndustriesRecommendedLazyRoute,
    AuthenticatedDashboardLogbookDetailsLazyRoute:
      AuthenticatedDashboardLogbookDetailsLazyRoute,
    AuthenticatedDashboardActivitiesIndexRoute:
      AuthenticatedDashboardActivitiesIndexRoute,
    AuthenticatedDashboardTeachersIndexRoute:
      AuthenticatedDashboardTeachersIndexRoute,
    AuthenticatedDashboardTrainingIndexRoute:
      AuthenticatedDashboardTrainingIndexRoute,
    AuthenticatedDashboardComplaintsIndexLazyRoute:
      AuthenticatedDashboardComplaintsIndexLazyRoute,
    AuthenticatedDashboardContractIndexLazyRoute:
      AuthenticatedDashboardContractIndexLazyRoute,
    AuthenticatedDashboardIndustriesIndexLazyRoute:
      AuthenticatedDashboardIndustriesIndexLazyRoute,
    AuthenticatedDashboardLogbookIndexLazyRoute:
      AuthenticatedDashboardLogbookIndexLazyRoute,
    AuthenticatedDashboardReportsIndexLazyRoute:
      AuthenticatedDashboardReportsIndexLazyRoute,
    AuthenticatedDashboardSchoolProfileIndexLazyRoute:
      AuthenticatedDashboardSchoolProfileIndexLazyRoute,
    AuthenticatedDashboardStudentsIndexLazyRoute:
      AuthenticatedDashboardStudentsIndexLazyRoute,
    AuthenticatedDashboardActivitiesWeekIdDateRoute:
      AuthenticatedDashboardActivitiesWeekIdDateRoute,
    AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRoute:
      AuthenticatedDashboardSchoolProfileAcademicYearsAcademicYearIdRouteLazyRoute,
    AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRoute:
      AuthenticatedDashboardSchoolProfileSectorTradeSectorTradeIdRouteLazyRoute,
    AuthenticatedDashboardActivitiesWeekIdIndexRoute:
      AuthenticatedDashboardActivitiesWeekIdIndexRoute,
    AuthenticatedDashboardStudentsStudentIdIndexRoute:
      AuthenticatedDashboardStudentsStudentIdIndexRoute,
    AuthenticatedDashboardTeachersTeacherIdIndexRoute:
      AuthenticatedDashboardTeachersTeacherIdIndexRoute,
    AuthenticatedDashboardTrainingTrainingIdIndexRoute:
      AuthenticatedDashboardTrainingTrainingIdIndexRoute,
    AuthenticatedDashboardReportsReportIdIndexLazyRoute:
      AuthenticatedDashboardReportsReportIdIndexLazyRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
