import { Report } from './types';

export const reports: Report[] = [
  {
    id: '1',
    type: 'certificate',
    title: 'Sina Gerard Nyirangarama Itd.',
    company: 'Sina Gerard Nyirangarama Itd.',
    company_district: 'Gakenke district',
    company_sector: 'Nyirangarama',
    timeline_from: '24 May 2024',
    timeline_to: '12 July 2024',
    status: 'Approved',
    thumbnailUrl: '/images/samples/certificate.png',
    fileUrl: 'https://elearning.reb.rw/pluginfile.php/11933/mod_resource/content/1/Economics%20S5%20SB.pdf',
  },
  {
    id: '2',
    type: 'certificate',
    title: 'Sina Gerard Nyirangarama Itd.',
    company: 'Sina Gerard Nyirangarama Itd.',
    company_district: 'Gakenke district',
    company_sector: 'Nyirangarama',
    timeline_from: '24 May 2024',
    timeline_to: '12 July 2024',
    status: 'Terminated',
    thumbnailUrl: '/images/samples/certificate.png',
    fileUrl: '/images/samples/certificate.pdf',
  },
  {
    id: '3',
    type: 'certificate',
    title: 'Sina Gerard Nyirangarama Itd.',
    company: 'Sina Gerard Nyirangarama Itd.',
    company_district: 'Gakenke district',
    company_sector: 'Nyirangarama',
    timeline_from: '24 May 2024',
    timeline_to: '12 July 2024',
    status: 'Approved',
    thumbnailUrl: '/images/samples/certificate.png',
    fileUrl: '/images/samples/certificate.pdf',
  },
  {
    id: '4',
    type: 'certificate',
    title: 'Sina Gerard Nyirangarama Itd.',
    company: 'Sina Gerard Nyirangarama Itd.',
    company_district: 'Gakenke district',
    company_sector: 'Nyirangarama',
    timeline_from: '24 May 2024',
    timeline_to: '12 July 2024',
    status: 'Pending',
    thumbnailUrl: '/images/samples/certificate.png',
    fileUrl: '/images/samples/certificate.pdf',
  },
  {
    id: '5',
    type: 'certificate',
    title: 'Sina Gerard Nyirangarama Itd.',
    company: 'Sina Gerard Nyirangarama Itd.',
    company_district: 'Gakenke district',
    company_sector: 'Nyirangarama',
    timeline_from: '24 May 2024',
    timeline_to: '12 July 2024',
    status: 'Approved',
    thumbnailUrl: '/images/samples/certificate.png',
    fileUrl: '/images/samples/certificate.pdf',
  },
];
