import { Teacher } from './type';

export const teachers: Teacher[] = [
  {
    id: '1',
    name: 'John Doe',
    province: 'Kigali',
    district: 'Kicukiro',
    phone: '0788888888',
    idNumber: '1000283',
    trade: 'Welding',
    level: 'Level 1',
    status: 'on-leave',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    qualification: 'A1',
    email: 'john.doe@example.com',
  },
  {
    id: '2',
    name: 'Jane Doe',
    province: 'Kigali',
    district: 'Kicukiro',
    phone: '0788888888',
    idNumber: '1000283',
    trade: 'Welding',
    level: 'Level 1',
    status: 'on-leave',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    qualification: 'A1',
    email: 'john.doe@example.com',
  },
  {
    id: '3',
    name: 'John Doe',
    province: 'Kigali',
    district: 'Kicukiro',
    phone: '0788888888',
    idNumber: '1000283',
    trade: 'Welding',
    level: 'Level 1',
    status: 'deactivated',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    qualification: 'A1',
    email: 'john.doe@example.com',
  },
  {
    id: '4',
    name: 'John Doe',
    province: 'Kigali',
    district: 'Kicukiro',
    phone: '0788888888',
    idNumber: '1000283',
    trade: 'Welding',
    level: 'Level 1',
    status: 'active',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    qualification: 'A1',
    email: 'john.doe@example.com',
  },
  {
    id: '5',
    name: 'John Doe',
    province: 'Kigali',
    district: 'Kicukiro',
    phone: '0788888888',
    idNumber: '1000283',
    trade: 'Welding',
    level: 'Level 1',
    status: 'active',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    qualification: 'A1',
    email: 'john.doe@example.com',
  },
  {
    id: '6',
    name: 'John Doe',
    province: 'Kigali',
    district: 'Kicukiro',
    phone: '0788888888',
    idNumber: '1000283',
    trade: 'Welding',
    level: 'Level 1',
    status: 'active',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    qualification: 'A1',
    email: 'john.doe@example.com',
  },
  {
    id: '7',
    name: 'John Doe',
    province: 'Kigali',
    district: 'Kicukiro',
    phone: '0788888888',
    idNumber: '1000283',
    trade: 'Welding',
    level: 'Level 1',
    status: 'active',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    qualification: 'A1',
    email: 'john.doe@example.com',
  },
  {
    id: '8',
    name: 'John Doe',
    province: 'Kigali',
    district: 'Kicukiro',
    phone: '0788888888',
    idNumber: '1000283',
    trade: 'Welding',
    level: 'Level 1',
    status: 'active',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    qualification: 'A1',
    email: 'john.doe@example.com',
  },
  {
    id: '9',
    name: 'John Doe',
    province: 'Kigali',
    district: 'Kicukiro',
    phone: '0788888888',
    idNumber: '1000283',
    trade: 'Welding',
    level: 'Level 1',
    status: 'deactivated',
    dateOfBirth: '1990-01-01',
    school: 'Kigali Institute of Science and Technology',
    qualification: 'A1',
    email: 'john.doe@example.com',
  },
];
