import { Contract } from './types';

export const contracts: Contract[] = [
  {
    id: '1',
    contractTitle: 'Student Accommodation with M_hotel',
    contractType: 'Accommodation Contract',
    partyA: 'Nyabihu Tvet',
    partyB: 'M_hotel',
    startDate: '24 May 2024',
    endDate: '12 July 2024',
    contractValueA: 'N/A',
    termsAndConditions: 'Standard accommodation terms apply.',
    digitalSignature: '',
    status: 'Approved',
  },
  {
    id: '2',
    contractTitle: 'Industrial Placement with Niyirangarama',
    contractType: 'Placement Contract',
    partyA: 'Nyabihu Tvet',
    partyB: 'Sina Gerard Niyirangarama',
    startDate: '24 May 2024',
    endDate: '12 July 2024',
    contractValueA: 'N/A',
    termsAndConditions: 'Standard placement terms apply.',
    digitalSignature: '',
    status: 'Terminated',
  },
  {
    id: '3',
    contractTitle: 'Industrial Placement',
    contractType: 'Placement Contract',
    partyA: 'Nyabihu Tvet',
    partyB: 'Sina Gerard Niyirangarama',
    startDate: '24 May 2024',
    endDate: '12 July 2024',
    contractValueA: 'N/A',
    termsAndConditions: 'Standard placement terms apply.',
    digitalSignature: '',
    status: 'Approved',
  },
  {
    id: '4',
    contractTitle: 'Industrial Placement',
    contractType: 'Placement Contract',
    partyA: 'Nyabihu Tvet',
    partyB: 'Sina Gerard Niyirangarama',
    startDate: '24 May 2024',
    endDate: '12 July 2024',
    contractValueA: 'N/A',
    termsAndConditions: 'Standard placement terms apply.',
    digitalSignature: '',
    status: 'Pending',
  },
];
